### ISSUE TITLE
connections.policies seems to be a required attribute

### ISSUE THREAD

**Issue by dberardo-com** [linux-system-roles/vpn#41]
not defining this variable results the mesh_conf script to break

**Comment by dberardo-com** [comment]
what should be used as a default var then?

**Comment by richm** [comment]
can you provide your settings, and the error message you are getting?

**Comment by dberardo-com** [comment]
wow, that was fast.

so i am using this config:

```
- hosts: hostgroup
  become: true
  become_user: root

  vars:
    vpn_opportunistic: true
    vpn_connections:
      - name: something
        auto: start
        hosts:
          myhost1:
            hostname: xxx.xxx.xxx.xxx
          myhost2:
            hostname: yyy.yyy.yyy.yyy
  tasks:
    - include_role:
        name: vpn
```

tasks are under a roles/vpn/ local folder

and i get get an error at this stage of the mesh_conf.yml:

```
- name: Set policies fact
  when: conn.policies is defined
  set_fact:
    policies: "{{ conn.policies | rejectattr('cidr', 'match', '^default$') | list }}"
```

which basically states that the conn.policies attribute is undefined (i can provide the exact log tomorrow if needed)

I am running ansible against Ubuntu 20.04 hosts using a Windows controller machine running Cygwin

**Comment by richm** [comment]
@ueno looks like a bug - the policies line should not cause an error if policies is not defined e.g. maybe something like this:
```
    policies: "{{ conn.policies | rejectattr('cidr', 'match', '^default$') | list if conn.policies is defined else [] }}"
```
and then on line 28, something similar:
```
      {% set pol = conn.policies | d([]) | selectattr('cidr', 'match', '^default$') | map(attribute='policy') | join(',') %}
```
or something like that.  We also need to add a test for this case - it looks like the test for mesh ensures that `conn.policies` is always defined - but the docs say it doesn't have to be defined - so we should have a test for that case.

@dberardo-com in the meantime, I think you can define the policies like this
```
    vpn_connections:
      - name: something
        auto: start
        hosts:
          myhost1:
            hostname: xxx.xxx.xxx.xxx
          myhost2:
            hostname: yyy.yyy.yyy.yyy
        policies:
          - policy: private-or-clear
            cidr: default
```
not sure - never tried this, just reading the docs
