### ISSUE TITLE
possibility to connect via IPSec Xauth PSK

### ISSUE THREAD

**Issue by dberardo-com** [linux-system-roles/vpn#69]
Fitzbox routers can act as IPsec VPN servers on standard ports, but they required the use of the Xauth PSK protocol since user authentication is needed.

is it possible to configure the playbook to achieve this?

and also: is it possible to establish a connection between one managed host and an external one, like in this case https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/assembly_configuring-vpn-connections-with-ipsec-by-using-the-rhel-vpn-system-role_securing-networks: 

```
Optional: Configure connections from managed hosts to external hosts that are not listed in the inventory file by adding the following section to the vpn_connections list of hosts:

    vpn_connections:
      - hosts:
          managed_node1:
          managed_node2: --> this node would go away
          external_node:
            hostname: 192.0.2.2
```
